# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "gmpoint"
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Dang"]
  s.date = "2013-02-06"
  s.description = "Help to point on Goolge Map Description"
  s.email = "peter@rubify.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".DS_Store",
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "app/assets/.DS_Store",
    "app/assets/javascripts/locations.js.coffee",
    "app/assets/stylesheets/locations.css",
    "app/helpers/gmpoint/gmpoint_helper.rb",
    "gmpoint.gemspec",
    "lib/generators/active_record/gmpoint_generator.rb",
    "lib/generators/active_record/templates/migration.rb",
    "lib/generators/gmpoint/gmpoint_generator.rb",
    "lib/generators/gmpoint/install_generator.rb",
    "lib/gmpoint.rb",
    "test/helper.rb",
    "test/test_gmpoint.rb"
  ]
  s.homepage = "http://github.com/dangluan/gmpoint"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Help to point on Google Map"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<geocoder>, [">= 0"])
      s.add_runtime_dependency(%q<new_responds_to_parent>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<geocoder>, [">= 0"])
      s.add_dependency(%q<new_responds_to_parent>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.2.1"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<geocoder>, [">= 0"])
    s.add_dependency(%q<new_responds_to_parent>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.2.1"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

